# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.NB <- function(y, x, xlev, ylev, weights, laplacesmooth = 1.0) {
    .Call(`_targeted_NB`, y, x, xlev, ylev, weights, laplacesmooth)
}

.predNB <- function(X, condprob, xord, multinomial, prior, threshold = 1E-3) {
    .Call(`_targeted_predNB`, X, condprob, xord, multinomial, prior, threshold)
}

.ode_solve <- function(f, input, init, par) {
    .Call(`_targeted_ode_solve`, f, input, init, par)
}

bin_logl <- function(y, a, x1, x2, par, weights, type = "rd", indiv = FALSE) {
    .Call(`_targeted_bin_logl`, y, a, x1, x2, par, weights, type, indiv)
}

bin_dlogl <- function(y, a, x1, x2, par, weights, type = "rd", indiv = FALSE) {
    .Call(`_targeted_bin_dlogl`, y, a, x1, x2, par, weights, type, indiv)
}

bin_pa <- function(y, a, x1, x2, par, type = "rd") {
    .Call(`_targeted_bin_pa`, y, a, x1, x2, par, type)
}

bin_dlogl_c <- function(y, a, x1, x2, par, weights, type = "rd", indiv = FALSE) {
    .Call(`_targeted_bin_dlogl_c`, y, a, x1, x2, par, weights, type, indiv)
}

bin_esteq <- function(y, a, x1, x2, pr, alpha, par, weights, type = "rd") {
    .Call(`_targeted_bin_esteq`, y, a, x1, x2, pr, alpha, par, weights, type)
}

bin_esteq_c <- function(y, a, x1, x2, x3, alpha, par, weights, type = "rd") {
    .Call(`_targeted_bin_esteq_c`, y, a, x1, x2, x3, alpha, par, weights, type)
}

ace_est <- function(y, a, x1, x2, theta, weights, offset, link = "identity") {
    .Call(`_targeted_ace_est`, y, a, x1, x2, theta, weights, offset, link)
}

fast_iid <- function(y, p, x1, weights, logistic = TRUE) {
    .Call(`_targeted_fast_iid`, y, p, x1, weights, logistic)
}

.clusterid <- function(id) {
    .Call(`_targeted_clusterid`, id)
}

.groupsum <- function(x, cluster, reduce = TRUE) {
    .Call(`_targeted_groupsum`, x, cluster, reduce)
}

.softmax <- function(lp, ref = TRUE, log = FALSE) {
    .Call(`_targeted_softmax`, lp, ref, log)
}

.pava <- function(y, x, weights) {
    .Call(`_targeted_pava`, y, x, weights)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_targeted_RcppExport_registerCCallable`)
})
