FROM quay.io/pypa/manylinux2010_x86_64

RUN yum install -y lapack-devel SuperLU-devel blas-devel \
	tmux mg && \
	rm -rf /tmp/*

RUN git clone https://github.com/kkholst/target /root/target && \
	cd /root/target; make init-submodules && \
	export OLDPATH=$PATH; export PATH=/opt/python/cp38-cp38/bin:$OLDPATH

RUN pip install cmake ninja auditwheel

WORKDIR /root/target

CMD bash
