FROM quay.io/pypa/manylinux2010_x86_64

RUN yum install -y make lapack-devel blas-devel python-devel \
	tmux mg && \
	rm -rf /tmp/*

ENV VER=cp38-cp38
ENV PYPATH=/opt/python/$VER/bin

RUN $PYPATH/pip install cmake ninja auditwheel

COPY build/export/target /root/target

WORKDIR /root/target

CMD bash
