---
title: "Prediction models - scoring and calibration"
author: Klaus Kähler Holst
date: "`r Sys.Date()`"
output:
  knitr:::html_vignette:
    fig_caption: yes
    fig_width: 5.15
    fig_height: 3.5
    fig_align: center
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Prediction models - scoring and calibration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
 collapse = TRUE,
 #dev="png",
 comment = "#>"
)
library(targeted)
```

Introduction
============

Model Scoring
------------

```{r irisex}
data(iris)
set.seed(1)
dat <- csplit(iris, 2)

g0 <- NB(Species ~ ., data=dat[[1]])
g1 <- NB(Species ~ Sepal.Width + Petal.Length, data=dat[[1]])
g2 <- NB(Species ~ Sepal.Width, data=dat[[1]])
pr0 <- predict(g0, newdata=dat[[2]], wide=TRUE)
pr1 <- predict(g1, newdata=dat[[2]], wide=TRUE)
pr2 <- predict(g2, newdata=dat[[2]], wide=TRUE)
table(colnames(pr1)[apply(pr1,1,which.max)], dat[[2]]$Species)
table(colnames(pr2)[apply(pr2,1,which.max)], dat[[2]]$Species)
```


```{r scoring1}
scoring(dat[[2]]$Species, NB1=pr1)
scoring(dat[[2]]$Species, pr0=pr0, pr1=pr1, pr2=pr2)
```
\(A\) ...

```{r scoring2}
library(ranger)
m1 <- ranger(Species ~ ., data=dat[[1]], num.threads=1, probability=TRUE)
pr3 <- predict(m1, data=dat[[2]], num.threads=1)$predictions
scoring(dat[[2]]$Species, pr3)
```

Cross validation - model comparison
-------------------------------------

```{r tuning}
rf_model <- function(...) {
  dots <- list(...)
  fit <- function(data)
    do.call(ranger, c(dots, list(data=data, num.threads=1)))
  pred <- function(object, newdata)
    predict(object, data=newdata, num.threads=1)$predictions
  list(fit=fit, pred=pred)
}

lm_model <- function(...) {
  list(function(data) lm(..., data=data))
}
```

Continuous response
```{r}
library(ranger)
models <- list(rf=rf_model(formula=Sepal.Length ~ .),
               lm=lm_model(Sepal.Length ~ .))
a <- cv(models, data=iris, response="Sepal.Length")
a
```

Categorical response
```{r tuning2}
models <- list(rf=rf_model(Species ~ ., probability=TRUE),
               nb=list(function(data, ...) NB(Species ~ ., data=data)))
a <- cv(models, data=iris, response="Species")
a
```

Model tuning
-----------------------

```{r modeltuning}
args <- expand.list(num.trees=c(100,200,300,400,500), mtry=1:3,
                    formula=Species ~ ., probability=TRUE)
models <- lapply(args, function(par) do.call(rf_model, par))

a <- cv(models, data=iris, response="Species")

cbind(coef(a), attr(args, "table")[,1:2])

```


Model calibration
========================

```{r ex1, echo=FALSE, fig.caption="..."}
plot(1:10)
```


<!-- ## if (data.table::is.data.table(newdata)) newdata <- as.data.frame(newdata) -->
<!-- ## pr1 <- predict(model, newdata=newdata, ...) -->
<!-- ## response <- with(model, model$response) -->
<!-- ## weight <- with(model, model$filter[[1]]) -->
<!-- ## cal1 <- calibration(pr1, newdata[,response], weights=newdata[,weight]) -->
<!-- ## calibrate(cal1, pr1, ...) -->


SessionInfo
============


```{r}
sessionInfo()
```
