---
title: "Prediction model class (`ml_model`)
author: "Klaus Kähler Holst, Benedikt Sommer"
date: "`r Sys.Date()`"
output:
  knitr:::html_vignette:
    fig_caption: yes
    fig_width: 5.15
    fig_height: 3.5
    fig_align: center
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Prediction models - scoring and calibration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
 collapse = TRUE,
 #dev="png",
 comment = "#>"
)
library("targeted")
```

# Introduction

```{r data}
data(pbc, package="survival")
```

Describe Mayo Clinic Primary Biliary Cholangitis Data...

In the following we are interested in predicting events (death or transplant)
before 2 years.

```{r}
pbc <- transform(pbc, y = (time < 730) * (status > 0))
```


```{r}
m0 <- predictor_glm(y ~ 1)
m1 <- predictor_glm(y ~ age + sex + bili + edema + albumin)
m2 <- predictor_nb(y ~ age + sex + bili + edema + albumin, kernel = TRUE)


```

```{r}
cv(list(benchmark = m0, glm = m1, nb = m2), data = pbc)
```

```{r calibration}

```







# Defining new learners with `predictor`

predictor()


## Methods
estimate
predict

# Built-in model wrappers

# Cross-validation

# Calibration

# Super Learners
