# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SupTest <- function(x) {
    .Call('_gof_SupTest', PACKAGE = 'gof', x)
}

L2Test <- function(x, t) {
    .Call('_gof_L2Test', PACKAGE = 'gof', x, t)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_gof_RcppExport_registerCCallable', PACKAGE = 'gof')
})
