name: R tests

on: [push]

jobs:
  r_targeted:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout repository incl. submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}
            !${{ env.R_LIBS_USER }}/pak
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("remotes","covr","pkgdown","rcmdcheck"), repos="https://cloud.r-project.org")
          remotes::install_deps("R-package/targeted", dep=T, upgrade=T)
        shell: Rscript {0}
      - name: Check
        run: |
          make r_check pkg=targeted
      - name: Upload Coverage to Codecov
        run: |
          covr::codecov(path="R-package/targeted", type="all")
        shell: Rscript {0}

